# Generated by Django 5.2.8 on 2025-11-29 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/', verbose_name='Zdjęcie')),
                ('is_main', models.BooleanField(default=False, verbose_name='Zdjęcie główne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Zdjęcie oferty',
                'verbose_name_plural': 'Zdjęcia ofert',
                'ordering': ['-is_main', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ikona (CSS class)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='marketplace.category', verbose_name='Kategoria nadrzędna')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Opis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('condition', models.CharField(choices=[('new', 'Nowy'), ('like_new', 'Jak nowy'), ('good', 'Dobry'), ('fair', 'Dostateczny'), ('poor', 'Do naprawy')], default='good', max_length=20, verbose_name='Stan')),
                ('status', models.CharField(choices=[('active', 'Aktywna'), ('sold', 'Sprzedana'), ('reserved', 'Zarezerwowana'), ('inactive', 'Nieaktywna')], default='active', max_length=20, verbose_name='Status')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Lokalizacja')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Liczba wyświetleń')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ostatnia aktualizacja')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='marketplace.category', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Oferty',
                'ordering': ['-created_at'],
            },
        ),
    ]
